# Generated by Django 5.2 on 2025-04-11 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIFTEH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='avr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIFTEH.avr'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
