# Generated by Django 5.2 on 2025-04-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIFTEH', '0003_alter_work_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='unit',
            field=models.CharField(choices=[('1', 'шт.'), ('2', 'комп.'), ('3', 'л.'), ('4', 'кг.'), ('5', 'м.')], max_length=10),
        ),
    ]
