<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-22 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('work', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=255)),
                ('M1', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M2', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M3', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M4', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M5', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M6', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M7', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M8', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M9', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M10', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M11', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M12', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Avr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.CharField(default='', max_length=500)),
                ('work_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIFTEH.object')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField()),
                ('result', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='services_foto/')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIFTEH.object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('1', 'шт.'), ('2', 'комп.'), ('3', 'л.'), ('4', 'кг.'), ('5', 'м.')], max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('avr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIFTEH.avr')),
            ],
        ),
    ]
=======
# Generated by Django 4.2.5 on 2025-04-13 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.CharField(default='', max_length=500)),
                ('work_id', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('work', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=255)),
                ('M1', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M2', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M3', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M4', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M5', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M6', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M7', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M8', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M9', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M10', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M11', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('M12', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('1', 'шт.'), ('2', 'комп.'), ('3', 'л.'), ('4', 'кг.'), ('5', 'м.')], max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('avr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIFTEH.avr')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField()),
                ('result', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='services_foto/')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIFTEH.object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='avr',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIFTEH.object'),
        ),
        migrations.AddField(
            model_name='avr',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
>>>>>>> bubuka
