# Generated by Django 4.2.5 on 2025-04-20 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LIFTEH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='LIFTEH.object')),
            ],
        ),
    ]
