# Generated by Django 4.2.5 on 2025-04-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIFTEH', '0002_diagnostic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='estimate_date',
            new_name='end_date',
        ),
    ]
