# Generated by Django 5.2 on 2025-05-07 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIFTEH', '0002_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='fact_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='avr',
            name='work_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='insert_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата ввода'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='result',
            field=models.IntegerField(blank=True, null=True, verbose_name='Результат'),
        ),
    ]
