# Generated by Django 5.2 on 2025-08-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIFTEH', '0006_object_latitude_object_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='folder_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
