# Generated by Django 5.2.7 on 2026-01-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIFTEH', '0010_object_serial_number_alter_problem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=300)),
                ('number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('financing', models.CharField(choices=[('own', 'Собственные'), ('budget', 'Бюджетные')], default='own', max_length=20)),
                ('longtime', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='object',
            name='dogovor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LIFTEH.dogovor', verbose_name='Договор'),
        ),
    ]
