name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.2'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r LIFTEH_project/requirements.txt
    
    - name: Run tests
      run: |
        python manage.py test
