name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.6", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Debug directory structure
      run: ls -R
    - name: Install Dependencies
      run: |
      working-directory: ./LIFTEH_project
        python -m pip install --upgrade pip
        pip install -r LIFTEH_project/requirements.txt
    - name: Run Tests
      run: |
        cd LIFTEH_project
        python manage.py test
