name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Change to project directory
        run: |
          cd LIFTEH_project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: settings
          SECRET_KEY: "django-insecure-test-key-for-ci-${{ github.run_id }}"
          DEBUG: "True"
        run: |
          python manage.py migrate

      # - name: Run tests
      #   env:
      #     DJANGO_SETTINGS_MODULE: settings
      #     SECRET_KEY: "django-insecure-test-key-for-ci-${{ github.run_id }}"
      #     DEBUG: "True"
      #   run: |
      #     python manage.py test