name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04  # Более старая версия Ubuntu с совместимыми библиотеками
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Python 3.6
      run: |
        apt-get update
        apt-get install -y python3.6 python3-pip
        python3.6 -m pip install --upgrade pip
    
    - name: Install dependencies
      run: |
        python3.6 -m pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python3.6 manage.py test