name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    container:
      image: python:3.6-slim-buster  # Используем Docker-контейнер с Python 3.6
    
    steps:
    - uses: actions/checkout@v4

    - name: Debug structure
      run: |
        echo "Python: $(python --version)"
        ls -R

    - name: Install dependencies
      working-directory: ./LIFTEH_project
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: ./LIFTEH_project
      run: |
        python manage.py test
