name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04  # Используем более старую версию Ubuntu
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.6
      uses: actions/setup-python@v5
      with:
        python-version: '3.6.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python manage.py test