name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.6-slim-buster  # Официальный образ с Python 3.6
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      working-directory: ./LIFTEH_project
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: ./LIFTEH_project
      run: |
        python manage.py test
