name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-20.04  # Требуется для Python 3.6
    container:
      image: python:3.6-slim-buster  # Используем официальный образ

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      run: |
        python -m pip install --upgrade "pip<21.3"  # Совместимая версия pip
        mkdir -p /home/python/.cache/pip
        chown -R python:python /home/python/.cache

    - name: Install dependencies
      working-directory: ./LIFTEH_project
      run: |
        # Устанавливаем совместимые версии пакетов
        echo "asgiref==3.2.10" >> requirements.txt
        echo "Django==2.2.24" >> requirements.txt
        
        pip install --user -r requirements.txt
        export PATH="$HOME/.local/bin:$PATH"

    - name: Run tests
      working-directory: ./LIFTEH_project
      run: |
        python manage.py test
