name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.6"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Debug directory structure
      run: |
        echo "Current working directory: $(pwd)"
        ls -R

    - name: Install Dependencies
      working-directory: ./LIFTEH_project  # Перенесено на уровень шага
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Путь относительный к working-directory

    - name: Run Tests
      working-directory: ./LIFTEH_project
      run: |
        python manage.py test
