name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    container:
      image: python:3.6-slim-buster
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug info
        run: |
          echo "Python version: $(python --version)"
          echo "Working directory: $(pwd)"
          ls -R

      - name: Install dependencies
        working-directory: ./LIFTEH_project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: ./LIFTEH_project
        run: |
          python manage.py test
